### ISSUE TITLE
Map custom obo format formalization of properties to LinkML or other formalisms

### ISSUE THREAD

**Issue by cmungall** [jmchandonia/CORAL#24]
context_measurement_ontology.obo uses obo format creatively:

```yaml
id: ME:0000346
name: Organic
namespace: measure.ontology
property_value: data_type "boolean" xsd:string
property_value: is_microtype "true" xsd:boolean
property_value: is_valid_data_variable "true" xsd:boolean
property_value: is_valid_property "true" xsd:boolean
def: "Use as context, for example, to label inorganic or organic carbon." []
is_a: ME:0000026 ! Chemical Context
```

This is syntactically valid but the properties are non-standard, and is using obo format for something it's not intended for.

This could be represented in LinkML as:

```yaml
slots:
  organic:
    range: boolean
    description: Use as context, for example, to label inorganic or organic carbon.
    annotations:
       is_microtype: true  
```

This can be converted back to obo/owl using standard LinkML tools, but the default rendering is a bit different.

I propose writing some simple python to convert the ME terms to LinkML, allowing them to be used within other tooling. The SoT can remain as bespoke obo since that is presumably easier for CORAL use cases.
